### PR TITLE
Implement CustomRelTime

### PR DESCRIPTION
**Pull request by dustin**
for #25

---
This change is [Reviewable](https://reviewable.io/reviews/dustin/go-humanize/33)

### CODE REVIEW

**Comment by shurcooL** [comment]
Is this based on #26? How similar is it, and what are the differences?

**Comment by dustin** [comment]
Heh, well, no.  I'd forgotten about that one.  :/  I just sat down on the
bus and wrote it from scratch today.  That's a little embarrassing.  I'm
glad I sent it out for review.  :)

**Comment by shurcooL** [comment]
I think having 2 implementations will help us find a more optimal final solution, by taking best ideas/pieces from both. But it does mean a little more work consolidating them.

**Comment by dustin** [comment]
Apologies for doing that.  I just saw a note and was bored on the bus.  Feel free to abandon mine, or whatever makes sense.

**Comment by shurcooL** [comment]
I don't see a need to apologize. I think your implementation is likely better to go with, since you wrote this package in the first place and have better context on what fits in. But I haven't reviewed it in detail yet.

**Comment by dustin** [comment]
Please don't take that into consideration.  If anything, someone else's
work is more valuable than mine.  I already did a bunch.

Whatever makes sense.  There are at least three options here. :)

**Comment by shurcooL** [comment]
@dustin, according to https://github.com/dustin/go-humanize/pull/26#issuecomment-234171134, you ended up merging #26 with a modified version of this commit on top.

So it should be safe to delete the `custime` branch now. I'll do that in order to clean up. If it's needed again, it can be restored from this PR.

**Pull request closed without merging**
