### PR TITLE
Make it compatible again with go < 1.5

### PR DESCRIPTION
**Pull request by tucksaun**
Since https://github.com/dustin/go-humanize/commit/c447c0d5900e8b1bea327c219fa5d3cba45ba234, `go-humanize` is not compatibly anymore with Go <1.5.
I know, it's an old version, but right now I'm still stuck with it :(

This fixes it, while keeping the feature for more up-to-date versions.

### CODE REVIEW

**Comment by shurcooL** [comment]
The `big.Float` struct was introduced in 1.5 only.

This looks reasonable, and not a lot added maintenance to support. The API will be slightly smaller in 1.4 and older (but better than it not building at all), but I don't see a better way of resolving this. LGTM.

**Comment by dustin** [comment]
Awesome, I was hoping there was a way to do this, but wasn't aware of the version-specific build constraints.

`am`'d and pushed.

**Comment by tucksaun** [comment]
Great! Wasn't sure this was something you'd like for go-humanize.

Thanks for the quick merge and thanks for the lib too :)

**Comment by shurcooL** [comment]
Bummer, I missed/forgot about this during code review.

But we should also move `TestBigCommafs` behind the build flag, otherwise test will fail on older versions of Go.

**Pull request closed without merging**
