### PR TITLE
Add Travis CI.

### PR DESCRIPTION
**Pull request by shurcooL**
Run go fmt, go vet and go test with -race checks. Run on tip with allowed failure and fast finish.

Add badges to README.

### CODE REVIEW

**Comment by shurcooL** [comment]
@dustin, I think you'll need to activate this repo on Travis at https://travis-ci.org/dustin/go-humanize. It's free.

**Comment by dustin** [comment]
Is there a way to do this without a .travis.yml?  I used to do that, but it's kind of messy.  I started using drone.io because they don't dirty up the repo just to do a build.  However, drone.io hasn't updated in a while.

**Comment by shurcooL** [comment]
I think it might work without a .travis.yml, but only with the defaults. Which won't include anything like fmt check, vet, -race flag, etc.

I agree that a .travis.yml file is messy, but it seems there's no way around it if you want to be picky about what happens during your CI. At least I don't know of a way. If I did, I would get rid of all the .travis.yml files in my repos too. :)

Anyway, this PR is just a proposal; this is your repo so it's your call whether you want this or not. I just made it because I noticed there was no CI. I've done similar PRs like https://github.com/gorilla/mux/pull/134, https://github.com/google/go-github/pull/346, etc., so it wasn't hard for me (in fact, it's generated using a [tool](https://godoc.org/github.com/shurcooL/cmd/gorepogen); I didn't write it by hand).

**Comment by dustin** [comment]
Alright.  I think it's messy, but it's useful.

**Comment by shurcooL** [comment]
Sounds good. 👍

For posterity, this PR was merged as 5fe2da158d3f75587f1064fb5b1eda80c2281225.

**Pull request closed without merging**
