### PR TITLE
Add a few funcs for limiting the number of decimal places outputted #18

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by dustin** [comment]
Sorry I sat on this for a while. Been super behind on a bunch of projects.

I did see that this had a small coverage miss, so I followed it up with a quickcheck test to assert few properties over it (and also used that to verify the previously non-covered code was essential).

**Comment by dustin** [comment]
I've included this as it also seemed to solve a limitation I ran into elsewhere.  Thanks.

**Comment by bramp** [comment]
Thanks.

**Comment by shurcooL** [comment]
For posterity (since it's not very visible), this was merged via commit 41f808901d8eb7d8d4e70a79b62b0d1b504e3f9a.

**Pull request closed without merging**
