### PR TITLE
Feature format number

### PR DESCRIPTION
**Pull request by flexd**
This has been useful in a number of projects and I think go-humanize is a suitable home.

See examples here http://play.golang.org/p/LXc1Ddm1lJ
Much thanks to @gorhill for original code :+1:

### CODE REVIEW

**Comment by dustin** [comment]
Could use a bit more test coverage if possible.

I also smashed these two changes together as to produce one logical change with tests.

**Comment by flexd** [comment]
What more test coverage would you like? I added a few more.

**Comment by dustin** [comment]
Well, I'd like to not reduce test coverage when adding new features.  There's currently no code in go-humanize that isn't covered by tests.  Last time I looked, this added code that wasn't covered, so it's either dead code, or bugs left to the user to discover.  :)

**Comment by flexd** [comment]
Hm, well unless code inside FormatFloat is counted and I have missed some possible inputs/outcomes, FormatInteger is just a wrapper around FormatFloat. I could add identical tests for that function as well.

**Comment by dustin** [comment]
go test -coverprofile=c.out && go tool cover -html=c.out

**Comment by flexd** [comment]
Ah I see, I will fix that.

**Comment by dustin** [comment]
Done, thanks!

**Pull request closed without merging**
